### PR TITLE
Text dublicate

### PR DESCRIPTION
**Pull request by eirenik0**
On the page https://websauna.org/features.html , you have same description text for both `Type hinting` and `One click deployment` sections.

### CODE REVIEW

**Comment by miohtama** [comment]
Thanks for this!

**Comment by eirenik0** [comment]
Hey, but I didn't write the correct text :) Why did you merge it?

**Comment by miohtama** [comment]
I trusted your judgement :)

**Comment by miohtama** [comment]
Feel free to open another PR to fix this PR ;)

**Comment by miohtama** [comment]
And happy holidays 🎅

**Comment by miohtama** [comment]
In Websauna we have "you break it, you buy it" rule 😄

**Pull request merged**
